### ISSUE TITLE
I suppose that the code comment should be remove.

### ISSUE THREAD

**Issue by zh25714** [Unbabel/OpenKiwi#96]
I suppose that the code comment should be removed.

`# token_type_ids[i, t_len : t_len + s_len] = 1`    in  kiwi/systems/encoders/xlmroberta.py line 424  interleave_input method.

>  """  
>       Interleave the source + target embeddings into one tensor.
> 
>         This means making the input as [batch, target [SEP] source]. 
> """

**Comment by captainvera** [comment]
Hello @zh25714 ,

Yeah, you are right, this isn't very clear. In reality this is not a problem because XLMR does not use token_type_ids. That is why it's commented out and the above sentence mentions that XLMR does not use NSP (next sentence prediction). You can also confirm [here](https://huggingface.co/transformers/model_doc/xlmroberta.html#transformers.XLMRobertaTokenizerFast.create_token_type_ids_from_sequences) 

This could be made clearer and the code removed. Could you make a PR? We would greatly appreciate it :)

**Comment by zh25714** [comment]
Thanks for your reply. I am a student studying QE through your kiwi system. That‘s good achitecture! I will make a PR if it's needed.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Miguel ***@***.***&gt;; 
发送时间: 2021年6月3日(星期四) 凌晨2:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Unbabel/OpenKiwi] I suppose that the code comment should be remove. (#96)





 
Hello @zh25714 ,
 
Yeah, you are right, this isn't very clear. In reality this is not a problem because XLMR does not use token_type_ids. That is why it's commented out and the above sentence mentions that XLMR does not use NSP (next sentence prediction). You can also confirm here
 
This could be made clearer and the code removed. Could you make a PR? We would greatly appreciate it :)
